version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: aiface_123
      POSTGRES_DB: face_attendance
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    ports:
      - '9000:9000' # S3 API
      - '9090:9090' # Web Console
    command: server /data --console-address ":9090"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: face-attendance-backend
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_FAMILY: ${REDIS_FAMILY}
    depends_on:
      - postgres
      - redis
    ports:
      - '3001:3001'
    command: ['npm', 'run', 'start:prod']

volumes:
  pgdata:
  minio-data:
